version: 2
  jobs:
    docker:
      - image: circleci/node:lts
    steps:
      - run: npm install
      - run: npm run update

workflows:
  version: 2
  build:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update
