on:
  schedule:
    - cron: 0 7/12 * * *
name: 📸 Update Twitter Picture
jobs:
  gitHubActionForNpm:
    name: Update Twitter Bio
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - run: npm i
    - run: npm run update-twitter-pic
      env:
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_API_PUBLIC_KEY: ${{ secrets.TWITTER_API_PUBLIC_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
