on:
  schedules:
  - cron: 0 0 * * *

name: Update Twitter Bio
jobs:
  gitHubActionForNpm:
    name: GitHub Action for npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for npm
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: i
    - name: GitHub Action for npm-1
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      env:
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_API_PUBLIC_KEY: ${{ secrets.TWITTER_API_PUBLIC_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
      with:
        args: run update-twitter-pic
