on:
schedule:
  - cron: 0 9/12 * * *
name: 📸 Screenshot twitter.com/JNYBGR
jobs:
  update:
    name: Update
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - run: |
        npm i
    - run: |
        npx ts-node src/screenshot-twitter.ts
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   